# Generated by Django 4.2.3 on 2023-07-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_form_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='image',
            new_name='receipt',
        ),
    ]
